### PR TITLE
[#95168192] Common registry playbook for GCE and AWS

### PR DESCRIPTION
**Pull request by mtekel**
Create unified registry role that can run on both GCE and AWS, so that we don't have to have two different site-<aws|gce> playbooks. Rename common.yml to site.yml, add new registry roles in the start of it and use the new site.yml in Makefile. Cleanup the leftovers.

### CODE REVIEW

**Comment by annashipman** [comment]
Which story?

**Comment by mtekel** [comment]
Updated.

**Comment by keymon** [comment]
[Same comment as what we discussed adding postgresql](https://github.com/alphagov/tsuru-ansible/pull/127#commitcomment-12250020), here `aws_registry_vars.yml` and `gce_registry_vars.yml` are actually group variables. 

As we add more and more of these files the project directory is getting messy.

Appart of that, the naming of the files is not consistent:
- `platform-aws.yml` and `platform-gce.yml`: IaaS at the end
- `postgres_common_vars.yml` `postgres_master_vars.yml`: "role" at the beginning, specific context (master/common) later.
- But `gce_registry_vars.yml` and `aws_registry_vars.yml`: IaaS at the beggining (specific part) and "role" after.

Makes more sense  `registry_gce_vars.yml` and `registry_aws_vars.yml`

**Comment by mtekel** [comment]
I wanted to make differences more explicit, hence I put the IAAS name in the beginning of the vars file (as IAAS is the main difference driver between the two vars files). And yes, this should be properly refactored into groups. This is the 1st step.

**Comment by keymon** [comment]
I am going to rebase this from master in order to be able to review it without destroying all the environments, as I built them with https://github.com/alphagov/tsuru-ansible/pull/128 in place.

**Comment by keymon** [comment]
About the PR description itself, I would explain better the context, motivation, related card and priorities.

**Comment by keymon** [comment]
Tested after rebasing with master. Tested recreating the registry server, and works fine.

Once the comments above get answered I will be happy to merge it.

**Comment by keymon** [comment]
I amend the commits 1c65a50960563bec1396562afb59aee00b6c8fd4 and d7e5aa70fa921379da6a6af587a8bd9d71db0653 to reflect the real actions

**Comment by mtekel** [comment]
Regarding postgres globals and common: The variable split was done already before I pulled the vars from the playbook into common. Someone for some reason has decided to split the variables this way and I had no reason to change this. 

Regarding file naming: We should probably discuss the ansible approach we want to take (groups/files/globals etc.), then come up with some naming guidelines and stick with them. Currently it's ad-hoc based on what seems a better name.

**Comment by keymon** [comment]
I disagree about:
- naming convention of `registry_gce_vars.yml / registry_aws_vars.yml` vs `gce_registry_vars.yml / aws_registry_vars.yml`. I do prefer the later.
- moving the variables to `globals.yml` as bfb0f288d84762afbd2a59c7526df0f9d6cdd107  . These variables are specific to the playbook of registry. I consider there should be either in:
  - in the `registry.yml` playbook, in a vars section as done in a lot of other playbooks.
  - in a separated file `registry_common_vars.yml` as in the postgres playbook.

**Comment by keymon** [comment]
After last changes, I'm happy now :) :+1:

**Pull request merged**
