### PR TITLE
[#91513820] Pull in updated tsuru-api playbook

### PR DESCRIPTION
**Pull request by actionjack**
[Application healing](https://www.pivotaltracker.com/story/show/91513820)

**What**

In order to make `Tsuru` autoheal we need to add two new settings:
- `healing_active_monitoring_interval` - Number of seconds between calls
  to `<server>/_ping` in each one of the docker nodes,
  [for more information check
  here](http://tsuru.readthedocs.org/en/stable/reference/config.html?highlight=unit#docker-healing-active-monitoring-interval)
- `healing_heal_containers_timeout` - Number of seconds a container
  should be unresponsive before triggering the recreation of the
  container, [for more information check
  here](http://tsuru.readthedocs.org/en/stable/reference/config.html?highlight=unit#docker-healing-heal-containers-timeout)

v0.0.4 of the [ansible-playbook-tsuru-api](https://github.com/alphagov/ansible-playbook-tsuru_api/pull/5)
adds support for the settings above.

**Who should review this PR**
- Anyone on the core team with the exception of @saliceti who I paired with :p

### CODE REVIEW

**Comment by dcarley** [comment]
It looks like the tag has been created from the PR branch, whereas it should be from `master` after the PR has been merged. That would prevent any confusion if the PR changes or `master` advances before it's merged.

**Comment by actionjack** [comment]
@dcarley yes I was trying to make it easier to test before it was merged in as described in this [PR](https://github.com/alphagov/ansible-playbook-tsuru_api/pull/5)

**Comment by keymon** [comment]
I tested and merged the upstream tsuru-api role. Merging this :)

**Comment by dcarley** [comment]
> @dcarley yes I was trying to make it easier to test before it was merged in as described in this PR

We might need to look at what's required to make testing of playbook changes easier, because I think premature tagging will create more problems than it solves.

**Pull request merged**
