### PR TITLE
[Fixes #94658242] Wrap commands in Makefile

### PR DESCRIPTION
**Pull request by dcarley**
Bit off piste. This is related to dynamic inventory, but also fixes another problem that we had a story for.
#### Move ansible-playbook commands to Makefile

These are getting quite complex, so we should move them to something more
automated to reduce the chance of human error.

By doing so we can also check that the environment name is set.

I realise that this disadvantages people using Linux instead of Mac because
they are forced to use `vault_password.sh` instead of their own solutions
like reading from a file. It seems like a reasonable compromise though.
#### Render ssh.config based on environment name

`ssh_config(5)` doesn't support interpolation of environment variables, so
we have been updating this by hand for each independent environment. This is
a pain and will become worse when we need to do the same in Jenkins. So
render it based on a crude template and `gitignore` the resulting file.

### CODE REVIEW

**Comment by mtekel** [comment]
Looks fine.

**Comment by annashipman** [comment]
It looks fine, but I am just testing it.

**Comment by annashipman** [comment]
This doesn't work for me, it fails with:

```
ERROR: Inventory script (gce.py) had an execution error: Traceback (most recent call last):
  File "/Users/annashipman/projects/govuk/multicloud/tsuru-ansible/gce.py", line 303, in <module>
    GceInventory()
  File "/Users/annashipman/projects/govuk/multicloud/tsuru-ansible/gce.py", line 111, in __init__
    self.driver = self.get_gce_driver()
  File "/Users/annashipman/projects/govuk/multicloud/tsuru-ansible/gce.py", line 187, in get_gce_driver
    gce = get_driver(Provider.GCE)(*args, **kwargs)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/libcloud/compute/providers.py", line 177, in get_driver
    return _get_provider_driver(DRIVERS, provider)
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/libcloud/utils/misc.py", line 44, in get_driver
    _mod = __import__(mod_name, globals(), locals(), [driver_name])
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 24, in <module>
    from libcloud.common.google import GoogleResponse
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/libcloud/common/google.py", line 81, in <module>
    from libcloud.utils.connection import get_response_object
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/libcloud/utils/connection.py", line 17, in <module>
    from libcloud.common.base import Connection
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/libcloud/common/base.py", line 51, in <module>
    from libcloud.httplib_ssl import LibcloudHTTPConnection
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/libcloud/httplib_ssl.py", line 28, in <module>
    import libcloud.security
  File "/opt/boxen/homebrew/lib/python2.7/site-packages/libcloud/security.py", line 68, in <module>
    (environment_cert_file))
ValueError: Certificate file  doesn't exist
```

I have merged in [Dan's recent PR](https://github.com/alphagov/tsuru-ansible/pull/43) to the branch I'm testing on.

**Comment by annashipman** [comment]
Will take another look tomorrow.

**Comment by annashipman** [comment]
I have added two commits. One was a merge from master as noted in my previous comment, and one was required for me to get the Makefile working.

It is now failing for me on SSH and I'm not sure why:

```
fatal: [anna2-tsuru-registry] => SSH Error: ssh_exchange_identification: Connection closed by remote host
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [aalda.docker-registry | Install base dependencies] *********************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/annashipman/site-gce.retry

anna2-tsuru-registry       : ok=0    changed=0    unreachable=1    failed=0

make: *** [gce] Error 3
```

However, it fails the same way without the Makefile so this is probably something else about my setup. 

Someone else should test this PR to see if it works for them.

**Comment by actionjack** [comment]
Works for me merging....

**Comment by dcarley** [comment]
> I'm not quite sure why this would have worked for Dan, but it didn't work for me; without the `shell` the python command wasn't being executed so Ansible could not find the certificate.

I didn't test that part. Sorry :panda_face:

**Pull request merged**
